name: 'Deploy Terrafrom Resource Group'

on:
  push:
    branches: [ "main" ]
  pull_request:

permissions:
  contents: read

jobs:
  deploy_resource_group:
    name: 'Deploy_resource_rg'
    env:
      AZ_CLIENT_ID: ${{ secrets.AZURE_AD_CLIENT_ID_}}
      AZ_CLIENT_SECRETS: ${{ secrets.AZURE_AD_SECRET_ID}}
      AZ_TENANT_ID: ${{ secrets.AZURE_AD_TENANT_ID}}
      AZ_SUBSCRIPTION_ID: ${{ secrets.AZURE_AD_SUBSCRIPTION_ID}}
    runs-on: ubuntu-latest
    environment: dev

